---
title: "Lab3"
format: md
---

## Цель работы

1.  Развить практические навыки использования языка программирования R для обработки данных
2.  Закрепить знания базовых типов данных языка R
3.  Развить практические навыки использования функций обработки данных пакета dplyr – функции select(), filter(), mutate(), arrange(), group_by()

## Исходные данные

1.  Rstudio Desktop;
2.  Интерпретатор языка R 4.1;
3.  Программный пакет `dplyr` и `knitr`.

## План

Проанализировать встроенный в пакет dplyr набор данных `nycflights13` с помощью языка R и ответить на вопросы.

## Решение:

1.  Сколько встроенных в пакет nycflights13 датафреймов?

{R}
```         
> length(ls("package:nycflights13"))
[1] 5
> ls("package:nycflights13")
[1] "airlines" "airports" "flights"  "planes"   "weather"
```

2.  Сколько строк в каждом датафрейме?

```         
> nrow(flights)
[1] 336776
> nrow(airlines)
[1] 16
> nrow(airports)
[1] 1458
> nrow(planes)
[1] 3322
> nrow(weather)
[1] 26115
```

3.  Сколько столбцов в каждом датафрейме?

```         
> ncol(flights)
[1] 19
> ncol(airlines)
[1] 2
> ncol(airports)
[1] 8
> ncol(planes)
[1] 9
> ncol(weather)
[1] 15
```

4.  Как просмотреть примерный вид датафрейма?

```         
> glimpse(flights)
Rows: 336,776
Columns: 19
$ year           <int> 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013, 2013,…
$ month          <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ day            <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,…
$ dep_time       <int> 517, 533, 542, 544, 554, 554, 555, 557, 557, 558, 558, 558, 558, 558, 559, 55…
$ sched_dep_time <int> 515, 529, 540, 545, 600, 558, 600, 600, 600, 600, 600, 600, 600, 600, 600, 55…
$ dep_delay      <dbl> 2, 4, 2, -1, -6, -4, -5, -3, -3, -2, -2, -2, -2, -2, -1, 0, -1, 0, 0, 1, -8, …
$ arr_time       <int> 830, 850, 923, 1004, 812, 740, 913, 709, 838, 753, 849, 853, 924, 923, 941, 7…
$ sched_arr_time <int> 819, 830, 850, 1022, 837, 728, 854, 723, 846, 745, 851, 856, 917, 937, 910, 7…
$ arr_delay      <dbl> 11, 20, 33, -18, -25, 12, 19, -14, -8, 8, -2, -3, 7, -14, 31, -4, -8, -7, 12,…
$ carrier        <chr> "UA", "UA", "AA", "B6", "DL", "UA", "B6", "EV", "B6", "AA", "B6", "B6", "UA",…
$ flight         <int> 1545, 1714, 1141, 725, 461, 1696, 507, 5708, 79, 301, 49, 71, 194, 1124, 707,…
$ tailnum        <chr> "N14228", "N24211", "N619AA", "N804JB", "N668DN", "N39463", "N516JB", "N829AS…
$ origin         <chr> "EWR", "LGA", "JFK", "JFK", "LGA", "EWR", "EWR", "LGA", "JFK", "LGA", "JFK", …
$ dest           <chr> "IAH", "IAH", "MIA", "BQN", "ATL", "ORD", "FLL", "IAD", "MCO", "ORD", "PBI", …
$ air_time       <dbl> 227, 227, 160, 183, 116, 150, 158, 53, 140, 138, 149, 158, 345, 361, 257, 44,…
$ distance       <dbl> 1400, 1416, 1089, 1576, 762, 719, 1065, 229, 944, 733, 1028, 1005, 2475, 2565…
$ hour           <dbl> 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,…
$ minute         <dbl> 15, 29, 40, 45, 0, 58, 0, 0, 0, 0, 0, 0, 0, 0, 0, 59, 0, 0, 0, 0, 10, 5, 10, …
$ time_hour      <dttm> 2013-01-01 05:00:00, 2013-01-01 05:00:00, 2013-01-01 05:00:00, 2013-01-01 05…
> 
```

5.  Сколько компаний-перевозчиков (carrier) учитывают эти наборы данных (представлено в наборах дан- ных)?

```         
> flights %>% 
+     summarise(n_unique = n_distinct(carrier))
# A tibble: 1 × 1
  n_unique
     <int>
1       16
```

6.  Сколько рейсов принял аэропорт John F Kennedy Intl в мае?

```         
> flights %>%
+     filter(dest == "JFK", month == 5) %>% 
+     nrow()
[1] 0
```

7.  Какой самый северный аэропорт?

```         
> airports %>%
+     arrange(desc(lat)) %>%
+     slice(1)
# A tibble: 1 × 8
  faa   name                      lat   lon   alt    tz dst   tzone
  <chr> <chr>                   <dbl> <dbl> <dbl> <dbl> <chr> <chr>
1 EEN   Dillant Hopkins Airport  72.3  42.9   149    -5 A     NA   
```

8.  Какой аэропорт самый высокогорный (находится выше всех над уровнем моря)?

```         
> airports %>%
+     arrange(desc(alt)) %>%
+     slice(1)
# A tibble: 1 × 8
  faa   name        lat   lon   alt    tz dst   tzone         
  <chr> <chr>     <dbl> <dbl> <dbl> <dbl> <chr> <chr>         
1 TEX   Telluride  38.0 -108.  9078    -7 A     America/Denver
```

9.  Какие бортовые номера у самых старых самолетов?

```         
> planes %>% 
+     filter(!is.na(year)) %>% 
+     arrange(year) %>% 
+     slice(1:10) %>% 
+     select(tailnum, year)
# A tibble: 10 × 2
   tailnum  year
   <chr>   <int>
 1 N381AA   1956
 2 N201AA   1959
 3 N567AA   1959
 4 N378AA   1963
 5 N575AA   1963
 6 N14629   1965
 7 N615AA   1967
 8 N425AA   1968
 9 N383AA   1972
10 N364AA   1973
```

10. Какая средняя температура воздуха была в сентябре в аэропорту John F Kennedy Intl (в градусах Цельсия).

```         
> weather %>%
+     filter(origin == "JFK", month == 9) %>%
+     mutate(temp_c = (temp - 32) * 5/9) %>%
+     summarise(mean_temp_c = mean(temp_c, na.rm = TRUE))
# A tibble: 1 × 1
  mean_temp_c
        <dbl>
1        19.4
```

11. Самолеты какой авиакомпании совершили больше всего вылетов в июне?

```         
> flights %>%
+     filter(month == 6) %>%
+     count(carrier, sort = TRUE) %>%
+     left_join(airlines, by = "carrier")
# A tibble: 16 × 3
   carrier     n name                       
   <chr>   <int> <chr>                      
 1 UA       4975 United Air Lines Inc.      
 2 B6       4622 JetBlue Airways            
 3 EV       4456 ExpressJet Airlines Inc.   
 4 DL       4126 Delta Air Lines Inc.       
 5 AA       2757 American Airlines Inc.     
 6 MQ       2178 Envoy Air                  
 7 US       1736 US Airways Inc.            
 8 9E       1437 Endeavor Air Inc.          
 9 WN       1028 Southwest Airlines Co.     
10 VX        480 Virgin America             
11 FL        252 AirTran Airways Corporation
12 AS         60 Alaska Airlines Inc.       
13 F9         55 Frontier Airlines Inc.     
14 YV         49 Mesa Airlines Inc.         
15 HA         30 Hawaiian Airlines Inc.     
16 OO          2 SkyWest Airlines Inc. 
```

12. Самолеты какой авиакомпании задерживались чаще других в 2013 году?

```         
> flights %>%
+     filter(dep_delay > 0) %>%
+     count(carrier, sort = TRUE) %>%
+     left_join(airlines, by = "carrier")
# A tibble: 16 × 3
   carrier     n name                       
   <chr>   <int> <chr>                      
 1 UA      27261 United Air Lines Inc.      
 2 EV      23139 ExpressJet Airlines Inc.   
 3 B6      21445 JetBlue Airways            
 4 DL      15241 Delta Air Lines Inc.       
 5 AA      10162 American Airlines Inc.     
 6 MQ       8031 Envoy Air                  
 7 9E       7063 Endeavor Air Inc.          
 8 WN       6558 Southwest Airlines Co.     
 9 US       4775 US Airways Inc.            
10 VX       2225 Virgin America             
11 FL       1654 AirTran Airways Corporation
12 F9        341 Frontier Airlines Inc.     
13 YV        233 Mesa Airlines Inc.         
14 AS        226 Alaska Airlines Inc.       
15 HA         69 Hawaiian Airlines Inc.     
16 OO          9 SkyWest Airlines Inc.   
```

## Оценка результата

В результате лабораторной работы мы проанализировали встроенный в пакет dplyr набор данных `nycflights13` с помощью языка R.

## Вывод

Таким образом, мы развили практические навыки использования языка программирования R для обработки данных, закрепили знания базовых типов данных языка R, развили практические навыки использования функций обработки данных пакета dplyr – функции select(), filter(), mutate(), arrange(), group_by().
